# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af5add73fecd4032efa7fa79e1f2fd54ed7ff1bd6a9a130cfcdffbc7e89c9c9ddaae42faa47e83bf5b1f1c35a2138bad3450aa05ca79f298d6c37b9ca833253e

test:
  secret_key_base: 8374a267fb111c965a004c053b52cc0fb73be2d49faf1f604aaaec1e22f0503a696143394a4c9d86ae243549406cca87d329ab7a03ec9edfcd138199998687e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
